apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: message-app
data:
  PORT: "5000"
  NODE_ENV: "production"
  CORS_ORIGIN: "http://localhost"
  ALLOWED_ORIGINS: "http://localhost,http://192.168.1.3,http://192.168.1.11"
